Sagas = ["Horizon","Yakuza", "Yie Ar Kung-Fu","Yo-kai Watch","Yooka-Laylee",
"Yoshi","You Don't Know Jack","Ys", "Yu-Gi-Oh!","Z","Zanac","Zaxxon",
"Zero Escape","Zill O'll", "Zombie Tycoon","Zone of the Enders","Zool",
"Zoombinis","Zoo Tycoon","Zork", "Zuma","Zumba Fitness", "1080° Snowboarding",
"1942","3D Ultra Minigolf","3-D Ultra Pinball","7th Dragon","A Boy and His Blob",
"Ace Attorney","Ace Combat","ActRaiser","Adventure Island","Adventures of Lolo",
"Aero Fighters","Aero the Acro-Bat","After Burner","Age of Empires","Age of Wonders",
"Airforce Delta","Aleste","Alex Kidd","Alien Breed","Alien Syndrome","Alone in the Dark",
"Alpine Racer","Altered Beast","Alundra","American McGee's Alice","America's Army",
"Amnesia","Amped","Angry Birds","Animal Crossing","Anno","Anomaly","Another Century's Episode",
"Another Code","Ape Escape","Arc the Lad","Arkanoid","ARMA","Armored Core","Army Men",
"Army of Two","Art Academy","Ar Tonelico","Asheron's Call","Asphalt","Assassin's Creed",
"Assault Heroes","Asteroids","Astro","Atelier","ATV Offroad Fury","Audiosurf","Avadon",
"Babylonian Castle Saga","Backyard Sports","Baldur's Gate","Bangai-O","Banjo-Kazooie",
"Baraduke","Bard's Tale","Baseball Stars","Bases Loaded","Batman","Battle Arena Toshinden",
"Battlefield","Battle Isle","Battlestations","Battletoads","Battlezone","Bayonetta","Beat Hazard",
"Beatmania","Bendy","Bejeweled","Big Brain Academy","Bionic Commando","BioShock","Bit.Trip",
"The Black Mirror","Black & White","Blaster Master","BlazBlue","Blazing Angels","Blinx",
"Blitz: The League","Blood","Blood Bowl","BloodRayne","Bloody Roar","Blue Dragon","Bobby Carrot",
"Boktai","Boku no Natsuyasumi","Bomberman","Bomb Jack","Bonk","Boom Blox","Border Break",
"Borderlands","Bosconian","Boulder Dash","BoxBoy!","Brain Age","Bravely","Breakout",
"Breath of Fire","Broken Sword","Brothers in Arms","Bubble Bobble","Bubsy","Budget Cuts",
"Burgertime","Burnout","Bushido Blade","Bus Simulator","Buster Bros.","Bust a Groove","Buzz!",
"Cabela's","Call of Duty","Call of Juarez","Candy Crush","Cannon Fodder","Capcom Vs. SNK",
"Carmageddon","Car Mechanic Simulator","Carmen Sandiego","Carnival Games","Castle Shikigami",
"Castlevania","Centipede","Championship Manager","Chaos Rings","Chase H.Q.","Chessmaster",
"Chibi-Robo!","Chivalry","Choplifter","Chrono","City Connection","Civilization","ClayFighter",
"Clicker Heroes","Clock Tower","Clockwork Knight","Clubhouse Games","Colin McRae Rally","Colony Wars",
"Columns","Combat Mission","Command & Conquer","Commandos","Company of Heroes","Condemned",
"The Conduit","Conker","Contra","Cooking Mama","Cool Boarders","Corpse Party","Cotton",
"Counter-Strike","Crackdown","Crash Bandicoot","Crazy Castle","Crazy Taxi",
"Creatures","The Crew","Crimson Skies","Croc","Cruis'n","Crusader Kings","Crush Pinball","Crysis",
"The Culling","Custom Robo","Cut the Rope","Cyber Sled","D","Dance Central","Dance Dance Revolution",
"Danganronpa","Darius","Dark Cloud","Dark Seed","Dark Souls","Darksiders", "Darkstalkers",
"Daytona USA","DC Comics","de Blob","Dead Frontier","Dead Island","Deadly Premonition",
"Dead or Alive","Dead Rising","Dead Space","Dead to Rights","Deathsmiles","DeathSpank",
"Deer Hunter","Defense Grid","Def Jam","Defender","Delta Force","Densha de Go!",
"Descent","Desperados","Destroy All Humans!","Deus Ex","Devil Children","Devil May Cry",
"Diablo","Dies irae","Dig Dug","Dino Crisis","Disaster Report","Disgaea","Dishonored",
"Disney Infinity","Dizzy","Donkey Kong","DonPachi","Doom","Dota","Double Dragon","Dragon Age",
"Dragon Ball","Dragon Buster","Dragon Force","Dragon Quest","Dragon Slayer","Dragon Spirit",
"Dragon's Lair","Drakengard","Drawn to Life","Dream Chronicles","Driver","Duke Nukem",
"Dungeon Defenders","Dungeon Explorer","Dungeon Keeper","Dungeon Siege","Dying Light",
"Dynasty Warriors","Earth Defense Force","Earthworm Jim","Ecco the Dolphin","El Dorado Gate",
"The Elder Scrolls","Elevator Action","Empire Earth","Eternal Champions","Etrian Odyssey",
"Europa Universalis","EverQuest","Everybody's Golf","Evil Genius","The Evil Within","eXceed",
"Excite","Exerion","Exit","EyeToy","F1 Circus","F-Zero","Fable","Fallout","Famicom Grand Prix",
"Famicom Tantei Club","Family Game Night","Family Party","Family Stadium",
"The Fancy Pants Adventures","Fantasy Zone","Far Cry","Far East of Eden","Farming Simulator",
"Fatal Frame","Fatal Fury","Fat Princess","F.E.A.R.","Fieldrunners","FIFA","Fighting Vipers",
"Final Fantasy","Final Lap","Fire Emblem","Five Nights at Freddy's","FlatOut","Flowers",
"Football Manager","Forza","Fossil Fighters","Frequency","Frogger","Front Mission","Frostpunk",
"Game Party","G-Police","Gabriel Knight","Gal Gun","Galaxian","Galaxy Force","Game Tengoku",
"Ganbare Goemon","Gauntlet","Gears of War","Gekisha Boy","Geneforge","Genpei Tōma Den",
"Geometry Wars","The Getaway","Gex","Ghosts 'n Goblins","Giana Sisters","Giga Wing",
"Glory of Heracles","God Eater","God of War","Golden Axe","Golden Sun","The Golf Club",
"Golly! Ghost!","Gothic","Gradius","Gran Turismo","Grand Theft Auto","Grandia","Groove Coaster",
"Ground Control","Growlanser","Guacamelee!","Guardian Heroes","Guild","Guild Wars","Guilty Gear",
"Guitar Hero","Gunbird","Gundam","Gunpey","Gunslinger Stratos","Gunstar Heroes","Gunvolt",".hack",
"Half-Life","Halo","Hammerin' Harry","Hang-On","Hard Drivin'","Harry Potter","Harvest Moon",
"Hatsune Miku: Project DIVA","Hat Trick Hero","Hearts of Iron","Hebereke","Heiankyo Alien",
"Herzog","Hexic","Hidden & Dangerous","Hitman","Homeworld","Hotline Miami","The House of the Dead",
"Hyperdimension Neptunia","Hydlide","Hydro Thunder","Icewind Dale","The Idolmaster",
"Ikari Warriors","Illusion","Image Fight","Imagine","Inazuma Eleven","Infamous","Infinity",
"Infinity Blade","International Superstar Soccer","Iron Soldier","Itadaki Street","Jagged Alliance",
"Jak and Daxter","Jake Hunter","James Bond","Jazz Jackrabbit","J.B. Harold","Jetpac","Jet Moto",
"Jet Set Radio","Joe & Mac","Joe Danger","The Journeyman Project","Juiced","Jumping Flash!",
"Just Cause","Just Dance","Kane & Lynch","Katamari","Keyboardmania","Kid Icarus","Kid Niki",
"KiKi KaiKai","Killer Instinct","Killing Floor","Killzone","Kinect Sports","Kingdom Hearts",
"The King of Fighters","King's Quest","Kirby","Kirby Fighters","Klonoa","Knights of the Old Temple",
"Kotoba no Puzzle","Kunio-kun","Kururin","Kyle Hyde","Lands of Lore","Langrisser","The Last Blade",
"Last Ninja","The Last of Us","League of Legends","Left 4 Dead","Legacy of Kain","Legend of Legaia",
"The Legendary Starfy","The Legend of Heroes","The Legend of Kage","The Legend of Zelda",
"Hyrule Warriors","Lego","Leisure Suit Larry","Lemmings","Lethal Enforcers","Life Is Strange",
"Lineage","Lips","LittleBigPlanet","Little Nightmares","Lode Runner","The Lord of the Rings",
"Lost Kingdoms","Lost Planet","The Lost Vikings","Lotus","LovePlus","Lucky's Tale","Lufia",
"Luigi","Lumines","Lunar","Madden NFL","Mafia","Magical Drop","Mana","Manhunt","Maniac Mansion",
"Mappy","Mario","Dr. Mario","Mario Kart","Mario Party","Mario sports","Mario RPG",
"Mario vs. Donkey Kong","Super Mario","Marvel","Marvel vs. Capcom","Mass Effect",
"Master of Orion","Math Blaster","Max Payne","MechAssault","MechWarrior",
"Medal of Honor","MediEvil","Mega Man","Megami Tensei","Mercenaries","Metal Gear","Metal Max",
"Metal Slug","Metro","Metroid","Microsoft Combat Flight Simulator","Microsoft Flight Simulator",
"Midnight Club","Midtown Madness","Might and Magic","Milon's Secret Castle","Minecraft",
"Mirror's Edge","MLB 2K","MLB: The Show","Momoko 120%","Momotaro Densetsu","Momotaro Dentetsu",
"Monaco GP","Monkey Island","Monster Hunter","Monster Rancher","Monster Truck Madness",
"Monument Valley","Mortal Kombat","Mother","Motocross Madness","MotoGP","Moto Racer",
"MotorStorm","Mount & Blade","Mr. Do!","Mr. Driller","MX vs. ATV","Myst","Mystery Dungeon",
"Myth","N","Namco Anthology","Namco Museum","Nancy Drew","Naruto: Ultimate Ninja","NASCAR",
"Navy Field","NBA 2K","NBA Live","NBA Jam","NCAA Football","Nectaris / Military Madness",
"Need for Speed","Nekopara","NES Remix","Neutopia","Neverwinter Nights","NFL 2K","NHL (EA Sports) ",
"Nidhogg","Ni no Kuni","Nights","Ninja Gaiden","Ninja JaJaMaru-kun","Nintendogs",
"Nobunaga's Ambition","No More Heroes","Numan Athletics","Oddworld","Ogre","Ōkami","One Piece",
"One Must Fall","Onimusha","Operation Wolf","Orcs Must Die!","The Oregon Trail",
"Osu! Tatakae! Ouendan","Otogi","Otomedius","Outlast","Out Run","Overcooked","Pac-Man",
"Pac-Man World","Panzer Dragoon","PaRappa the Rapper","Parasite Eve","Parkan","Parodius",
"Patapon","Pathologic","Payday","Peggle","Pengo","Penumbra","Perfect Dark","Persona","Petz",
"PGA Tour","Phantasy Star","Pikmin","Pillars of Eternity","Pilotwings","Pinball FX",
"Pirate Ship Higemaru","Pitfall!","PixelJunk","PlanetSide","Plants vs. Zombies","Point Blank",
"Pokémon","Pokémon Pinball","Pokémon Play It!","Pokémon Puzzle","PokéPark","Pokémon Snap",
"Pokémon Stadium","Pole Position","Pong","Populous","Portal","Postal","Power Pros","Power Stone",
"Prince of Persia","Princess Maker","Pro Evolution Soccer","Professor Layton","Project Gotham Racing",
"Project X Zone","Prototype","Psychonauts","Punch-Out!!","Pushmo","Putt-Putt","Puyo Puyo",
"Puzzle Bobble","Puzzle & Dragons","Puzzle League","Q*bert","Qix","Quake","Quest for Glory",
"R-Type","Raiden","Railroad Tycoon","Rakugaki Ōkoku","Rampage","Rally-X","Rastan","Ratchet & Clank",
"RayForce","Rayman","Raving Rabbids","R.C. Pro-Am","Red Dead","Red Faction","Red Steel",
"Resident Evil","Resistance","Retro Game Challenge","Return Fire","Rhythm Heaven","Rick Dangerous",
"Ridge Racer","Risen","Risk of Rain","Road Fighter","Road Rash","Robopon","Robot","Robotron: 2084",
"Rock Band","Rod Land","Rogue Legacy","RollerCoaster Tycoon","Rolling Thunder",
"Romance of the Three Kingdoms","RPG Maker","Rugby League","Rumble Roses","Rune Factory",
"Runescape","Rush","Rush'n Attack","Rygar","Sabreman","SaGa","Saints Row","Sakura Wars",
"Salamander","Sam & Max","Samurai Shodown","Samurai Warriors","Sanctum","Scene It?",
"Schoolgirl Strikers","Science Adventure","Scramble","Scribblenauts","Sea Battle","Seaman",
"Sega Ages","Sega Bass Fishing","Sega Rally","Sengoku Basara","Senran Kagura","Serious Sam",
"The Settlers","Shadowgate","Shadow Man","Shadow of the Beast","Shadow Warrior","Shank","Shantae",
"Shenmue","Shining","Shinobi","Shōnen Jump","Shoot Away","Silent Hill","Silent Scope","Silpheed",
"SimCity","Simple","The Sims","Sin and Punishment","SingStar","Skate","Skylanders","Sly Cooper",
"Snake Rattle 'n' Roll","Sniper Elite","Snowboard Kids","SOCOM","Soldier of Fortune",
"Sonic Blast Man","Sonic the Hedgehog","Soulcalibur","Space Channel 5","Space Harrier",
"Space Invaders","Space Quest","Speedball","Spider-Man","Splashdown","Splatoon","Splatterhouse",
"'Splosion Man","SpongeBob SquarePants","Spy Hunter","Spyro","SSX","S.T.A.L.K.E.R.","Star Control",
"Star Force","Star Fox","Star Luster","Star Ocean","Star Raiders","Star Wars","StarCraft",
"Star Soldier","StarTropics","State of Decay","SteamWorld","Steel Battalion","Steel Division",
"Steel Gunner","Story of Seasons","Street Fighter","Streets of Rage","Strider","Strikers 1945",
"Stronghold","Subnautica","Suikoden","Summon Night","Super Mega Baseball","Super Monkey Ball",
"Super Robot Wars","Super Smash Bros.","Supreme Commander","Surgeon Simulator","Sutte Hakkun",
"Swordquest","Syberia","Syphon Filter","System Shock","Taiko no Tatsujin","Taito Memories","Tak",
"Tales","Tank Battalion","Team Fortress","Tecmo Bowl","Teenage Mutant Ninja Turtles","Tekken",
"Tempest","Tenchu","Terra Cresta","Test Drive","Tetris","Thief","Thunder Ceptor","Thunder Cross",
"Thunder Force","Tiger Heli","Time Crisis","Time Pilot","TimeSplitters","Titanfall","Tobal","TOCA",
"ToeJam & Earl","Tokimeki Memorial","Tom Clancy's","Tom Clancy's The Division",
"Tom Clancy's Ghost Recon","Tom Clancy's H.A.W.X","Tom Clancy's Rainbow Six",
"Tom Clancy's Splinter Cell","Tomb Raider","Tomodachi Collection","Tony Hawk's","Torchlight",
"Total Annihilation","Total War","Touch! Generations","Touhou Project","Toukiden","Track & Field",
"Train Simulator","Transformers","Trauma Center","Trials","Tribes","Trine","Tropico",
"Truck Simulator","True Crime","Truxton","Turok","Turrican","TwinBee","Twisted Metal",
"Two Worlds","Ultima","Uncharted","Unravel","Unreal","Uridium","Valis","Valkyria Chronicles",
"Valkyrie","Valkyrie Profile","Vampire: The Masquerade","Vandal Hearts","Vanguard","Vectorman",
"Vib-Ribbon","Viewtiful Joe","Vigilante 8","Violence Fight","Virtua Cop","Virtua Fighter",
"Virtua Striker","Virtua Tennis","Virtual On","Viva Piñata","V-Rally","Wagan Land",
"The Walking Dead","Wangan Midnight","Warcraft","Warhammer 40,000","Warhammer Fantasy","Wario",
"WarioWare","Wario Land","Warlords","Wars","Wasteland","Watch Dogs","Wave Race",
"White Knight Chronicles","Wii","Wild Arms","Wing Commander","Winning Run","Wipeout",
"The Witcher","Wizardry","Wizards & Warriors","Wolf Fang","Wolfenstein","Wonder Boy",
"Wonder Momo","Wonder Project","World Heroes","World Stadium","Worms","Wrecking Crew","WWE 2K",
"X (Egosoft)","X (Nintendo)","Xanadu","X-COM","Xeno","Xenogears","Xenosaga","Xenoblade Chronicles","Xe"]

divider = "|"

games = ["Zero Dawn", "Forbidden West", "I", "II","III","Chains of Olympus", 
"Ghost of Sparta", "Ascension","Black Flag","Isolation","Madness Returns","2 Fast 2 Furious", 
"Tokyo Drift", "Infinity","Electric Boogaloo", "Brotherhood", "Revelations", "Rogue", "Syndicate",
"Origins","Odyssey", "Valhalla", "1942", "Vietnam", "Modern Combat", "Armored Fury", "Bad Company", 
"Heroes", "Back to Karkand", "Hardline", "Modern Warfare", "2", "3", "4", "5", "6", "World at War",
"Black Ops","Ghosts","Advanced Warfare"]

from random import choice

if __name__ == "__main__":
    #print(len(Sagas))
    # Format: Saga, total_games, games
    tot_games = len(games)
    saga_file = []
    for i in range(len(Sagas)):
        for j in range(tot_games):
            p = Sagas[i]
            q = p
            p+=": " + games[j]
            p = q + divider + p
            saga_file.append(p)
    for k in saga_file:
        print(k )
